all: amicable amicable_st

CC=gcc
CFLAGS=-Wall -c -I. -ggdb
LIBS=-pthread -lm

amicable.o: amicable.c
	$(CC) $(CFLAGS) amicable.c

amicable: amicable.o
	$(CC) -o amicable amicable.o $(LIBS)

amicable_st.o: amicable_st.c
	$(CC) $(CFLAGS) amicable_st.c

amicable_st: amicable_st.o
	$(CC) -o amicable_st amicable_st.o $(LIBS)

clean:
	rm -f *.o amicable_st amicable
